version: "3"
services:

  mysql:
    image: mysql
    container_name: mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "5432:3306"
    environment:
      - MYSQL_DATABASE=d6rk5ijgmvcf6q
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_ROOT_HOST='%'
    restart: unless-stopped
    volumes:
      - ./mysql:/var/lib/mysql

  conduitbackendtest:
    build:
      context: ./
      dockerfile: ./backend
    container_name: ConduitBackendTest
    ports:
      - "3000:3000"
    restart: unless-stopped

  realworldfrontendtest:
    build:
      context: ./
      dockerfile: ./frontend    
    container_name: RealworldFrontendTest
    ports:
      - "4100:4100"
    restart: unless-stopped